/* Bundles the web sources in web/ into a single self-contained
   assets/aurora.html (the page, also openable in a browser) and
   assets/aurora-bundle.js (the same markup as a JS module, which is what the
   WebView is handed). Run after editing anything in web/.
   Plain Node so it runs on Windows as well as macOS/Linux. */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

const HEAD = `<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content" />
<meta name="description" content="A two-sided live streaming experience for hosts and supporters." />
<title>Aurora</title>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700;800&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
<style>
`;

const BODY = `</style>
</head>
<body>
<main class="app">
<div id="top"></div>
<div id="scroll-root" class="lenis-viewport">
<div class="body" id="screen"></div>
</div>
<div class="nav" id="nav"></div>
</main>
<script>
`;

const INIT = `</script>
<script>
/* Smooth scrolling for #scroll-root, matching the previous Lenis setup. */
(function () {
  var wrapper = document.getElementById("scroll-root");
  var content = document.getElementById("screen");
  var lenis = new Lenis({
    wrapper: wrapper,
    content: content,
    eventsTarget: wrapper,
    autoRaf: true,
    duration: 0.9,
    smoothWheel: true,
    syncTouch: false,
    wheelMultiplier: 0.9,
  });
  new MutationObserver(function () { lenis.resize(); })
    .observe(content, { childList: true, subtree: true });
  document.addEventListener("aurora:navigate", function () {
    lenis.scrollTo(0, { immediate: true });
  });
})();
</script>
<!-- Loaded as a classic script so its inline onclick handlers keep resolving globals. -->
<script>
`;

const TAIL = `</script>
</body>
</html>
`;

const html =
  HEAD +
  read("web/vendor/lenis.css") +
  read("web/aurora.css") +
  read("web/app.css") +
  BODY +
  read("web/vendor/lenis.min.js") +
  INIT +
  read("web/aurora-runtime.js") +
  TAIL;

mkdirSync(join(root, "assets"), { recursive: true });
writeFileSync(join(root, "assets/aurora.html"), html);
writeFileSync(
  join(root, "assets/aurora-bundle.js"),
  "/* Generated by scripts/build-web.mjs from web/ - do not edit by hand. */\n" +
    "export default " + JSON.stringify(html) + ";\n"
);
console.log(`built assets/aurora.html (${html.length} bytes) + assets/aurora-bundle.js`);
