#!/usr/bin/env sh
# Bundles the web sources in web/ into a single self-contained assets/aurora.html,
# which is what the React Native WebView renders. Run after editing anything in web/.
set -e
cd "$(dirname "$0")/.."
OUT=assets/aurora.html
mkdir -p assets

{
cat <<'HEAD'
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content" />
<meta name="description" content="A two-sided live streaming experience for hosts and supporters." />
<title>Aurora</title>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700;800&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
<style>
HEAD
cat web/vendor/lenis.css
cat web/aurora.css
cat web/app.css
cat <<'BODY'
</style>
</head>
<body>
<main class="app">
<div id="top"></div>
<div id="scroll-root" class="lenis-viewport">
<div class="body" id="screen"></div>
</div>
<div class="nav" id="nav"></div>
</main>
<script>
BODY
cat web/vendor/lenis.min.js
cat <<'INIT'
</script>
<script>
/* Smooth scrolling for #scroll-root, matching the previous Lenis setup. */
(function () {
  var wrapper = document.getElementById("scroll-root");
  var content = document.getElementById("screen");
  var lenis = new Lenis({
    wrapper: wrapper,
    content: content,
    eventsTarget: wrapper,
    autoRaf: true,
    duration: 0.9,
    smoothWheel: true,
    syncTouch: false,
    wheelMultiplier: 0.9,
  });
  new MutationObserver(function () { lenis.resize(); })
    .observe(content, { childList: true, subtree: true });
  document.addEventListener("aurora:navigate", function () {
    lenis.scrollTo(0, { immediate: true });
  });
})();
</script>
<!-- Loaded as a classic script so its inline onclick handlers keep resolving globals. -->
<script>
INIT
cat web/aurora-runtime.js
cat <<'TAIL'
</script>
</body>
</html>
TAIL
} > "$OUT"

echo "built $OUT ($(wc -c < "$OUT") bytes)"

# Also emit the bundle as a JS module, which is what the WebView is handed.
node -e 'const fs=require("fs");const h=fs.readFileSync("assets/aurora.html","utf8");fs.writeFileSync("assets/aurora-bundle.js","/* Generated by scripts/build-web.sh from web/ - do not edit by hand. */\nexport default "+JSON.stringify(h)+";\n");console.log("built assets/aurora-bundle.js")'
